name: Build and Deploy

on:
    push:
        branches:
            - "master"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: |
                    hasbii/restoku

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push image
              uses: docker/build-push-action@v5
              with:
                  file: ./Dockerfile
                  context: ./
                  push: ${{ github.event_name != 'pull_request' }}
                  tags: hasbii/restoku:latest
                  labels: ${{ steps.meta.outputs.labels }}

    deploy:
        runs-on: ubuntu-latest

        needs: build

        steps:
            - name: SSH & Docker Compose
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.SSH_USERNAME }}
                  key: ${{ secrets.SSH_KEY }}
                  port: ${{ secrets.SSH_PORT }}
                  script: |
                      cd ${{ secrets.PATH }} && docker compose down && (docker image rm hasbii/restoku:latest || true) && docker compose up -d

    migration:
            runs-on: ubuntu-latest

            needs: deploy

            steps:
                - name: SSH & Migration
                  uses: appleboy/ssh-action@v1.0.0
                  with:
                      host: ${{ secrets.SSH_HOST }}
                      username: ${{ secrets.SSH_USERNAME }}
                      key: ${{ secrets.SSH_KEY }}
                      port: ${{ secrets.SSH_PORT }}
                      script: |
                        docker exec Restoku npx prisma migrate deploy
